# This file is covered by the LICENSE file in the root of this project.
labels: 
  0 : "unlabeled"
  1 : "outlier"
  10: "car"
  49: "floor"
  50: "wall"
  51: "ceiling"
  80: "pillar"
color_map: # bgr
  0 : [0, 0, 0]
  1 : [255, 3, 242]
  10: [255, 0, 0]
  49: [171, 171, 171]
  50: [100, 150, 245]
  51: [59, 168, 5]
  80: [255, 140, 0]
content: # as a ratio with the total number of points
  0: 0.018889854628292943
  1: 0.0002937197336781505
  10: 0.040818519255974316
  49: 0.0039048553037472045
  50: 0.1326861944777486
  51: 0.0723592229456223
  80: 0.002855498193863172
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0 : 0     # "unlabeled"
  1 : 0     # "outlier" mapped to "unlabeled"
  10: 1     # "car"
  49: 2     # "floor"
  50: 3     # "wall"
  51: 4     # "ceiling"
  80: 5     # "pillar"
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled"
  1: 10     # "car"
  2: 49     # "floor"
  3: 50     # "wall"
  4: 51     # "ceiling"
  5: 80     # "pillar"
learning_ignore: # Ignore classes
  0: True      # "unlabeled"
  1: False     # "car"
  2: False     # "floor"
  3: False     # "wall"
  4: False     # "ceiling"
  5: False     # "pillar"
split: # sequence numbers
  train:
    - 0
    - 1
  valid:
    - 2
  test:
    - 2
